void atomic(){
	//Period 8 elements
	TFile *f=new TFile("atomic.root","recreate");
	TTree *t1=new TTree("t1","PeriodicTable");
	Float_t atmass,mp,bp;
	Int_t group,period,num;
	string name,symbol,state,descr;
	t1->Branch("num",&num,"num/I");
	t1->Branch("name",&name,"name/S");
	t1->Branch("symbol",&symbol,"symbol/S");
	t1->Branch("group",&group,"group/I");
	t1->Branch("period",&period,"period/I");
	t1->Branch("state",&state,"state/S");
	t1->Branch("descr",&descr,"descr/S");
	t1->Branch("atmass",&atmass,"atmass/F");
	t1->Branch("mp",&mp,"mp/F");
	t1->Branch("bp",&bp,"bp/F");
	//filling tree
	num=2;
	name="Helium";
	symbol="He";
	group=18;
	period=1;
	state="Gas";
	descr="Noble-gas";
	atmass=4.002602;
	mp=-272.226;
	bp=-268.934;
	t1->Fill();
	num=10;
	name="Neon";
	symbol="Ne";
	group=18;
	period=2;
	state="Gas";
	descr="Noble-gas";
	atmass=20.1797;
	mp=-248.67;
	bp=-246.048;
	t1->Fill();
	num=18;
	name="Argon";
	symbol="Ar";
	group=18;
	period=3;
	state="Gas";
	descr="Noble-gas";
	atmass=39.948;
	mp=-189.2;
	bp=-185.7;
	t1->Fill();
	num=2;
	name="Helium";
	symbol="He";
	group=18;
	period=1;
	state="Gas";
	descr="Noble-gas";
	atmass=4.002602;
	mp=-272.226;
	bp=-268.934;
	t1->Fill();
	num=36;
	name="Krypton";
	symbol="Kr";
	group=18;
	period=4;
	state="Gas";
	descr="Noble-gas";
	atmass=83.798;
	mp=-156.6;
	bp=-152.3;
	t1->Fill();
	num=54;
	name="Xenon";
	symbol="Xe";
	group=18;
	period=5;
	state="Gas";
	descr="Noble-gas";
	atmass=131.293;
	mp=-111.9;
	bp=-107.1;
	t1->Fill();
	num=86;
	name="Radon";
	symbol="He";
	group=18;
	period=6;
	state="Gas";
	descr="Noble-gas";
	atmass=-1;
	mp=-71;
	bp=-61.8;
	t1->Fill();
	t1->Write();
	cout<<"Done!"<<endl;
}
	

	
